const express = require('express'),
morgan = require('morgan'),
path = require('path'),
PORT = process.env.PORT || 8080,
expressSession = require('express-session'),
cookieParser = require('cookie-parser'),
mongoose = require('mongoose'),